### ISSUE TITLE
Non-normative security and privacy unacceptable

### ISSUE THREAD

**Issue by hchavers** [GPSecretariat/WebApis-for-se#27]
### Comments from Trusted Computing Group - Item #  8

**Section:** 4. Security and Privacy Considerations

**Comment:** Re “This section is non-normative.”  -

**Proposed Resolution:** It's unacceptable to make Security and Privacy Considerations non-normative - they MUST be normative or should be omitted entirely as useless.

**Comment by opoto** [comment]
Security and Privacy are addressed throughout the whole  document, they are the main focus of this specification. However section 4 is non-normative because it only contains explanatory information to help readers to better understand the scope of this specification. It answers questions that were raised by previous reviewers of this specification.
